[book]
language = "en"
src = "."
title = "pokehns-expansion"

[output.html]
git-repository-url = "https://https://github.com/TixoRebel/pokehns-expansion"
edit-url-template = "https://https://github.com/TixoRebel/pokehns-expansion/edit/main/docs/{path}"
site-url = "/pokehns-expansion/"

[preprocessor.fix_links]
command = "python3 fix_links.py"
after = [ "links" ]
